EARTH_RADIUS = 6378
class DataConstantString:
    time = "time"
    latitude = "latitude"
    longitude = "longitude"
    depth = "depth"
    mag = "mag"
    magType = "magType"
    nst = "nst"
    gap = "gap"
    dmin = "dmin"
    rms = "rms"
    net = "net"
    id = "id"
    updated = "updated"
    place = "place"
    type = "type"
    horizontalError = "horizontalError"
    depthError = "depthError"
    magError = "magError"
    magNst = "magNst"
    status = "status"
    locationSource = "locationSource"
    magSource = "magSource"
    distance = "distance"
    min_distance = "min_distance"
    year = "year"
    datetime = "datetime"

class PolicyConstantString:
    asset_locations = "asset_locations"
    max_radius = "max_radius"
    min_magnitude = "min_magnitude"
    protection_layers = "protection_layers"

